"use client";

import React, { useEffect, useState, useRef } from "react";
import { useParams, useRouter } from "next/navigation";
import styles from "./map-detail.module.css";

function storageKey(projectId) {
  return `brew3d:project:${projectId}:maps`;
}

function readMaps(projectId) {
  try {
    const raw = localStorage.getItem(storageKey(projectId));
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

function writeMaps(projectId, maps) {
  try {
    localStorage.setItem(storageKey(projectId), JSON.stringify(maps));
    window.dispatchEvent(new StorageEvent("storage", { key: storageKey(projectId) }));
  } catch {}
}

const MAP_TYPES = [
  { id: '2d-map', name: '2D Map', icon: '🗺️' },
  { id: '2d-boardgame', name: '2D Boardgame', icon: '🎲' },
  { id: '3d-voxel', name: '3D Voxel', icon: '🧱' },
  { id: '3d-realistic', name: '3D Realistic', icon: '🌍' },
  { id: '3d-animated', name: '3D Animated', icon: '✨' }
];

export default function MapDetailPage() {
  const { id, mapId } = useParams();
  const router = useRouter();
  const [map, setMap] = useState(null);
  const [maps, setMaps] = useState([]);
  const [isEditingName, setIsEditingName] = useState(false);
  const [mapName, setMapName] = useState("");
  const [showCombineModal, setShowCombineModal] = useState(false);
  const [selectedMaps, setSelectedMaps] = useState([]);
  const [showAIModal, setShowAIModal] = useState(false);
  const [aiPrompt, setAiPrompt] = useState("");
  const [isAIGenerating, setIsAIGenerating] = useState(false);
  const fileInputRef = useRef(null);
  const canvasRef = useRef(null);

  useEffect(() => {
    const allMaps = readMaps(id);
    setMaps(allMaps);
    const foundMap = allMaps.find(m => m.id === mapId);
    if (foundMap) {
      setMap(foundMap);
      setMapName(foundMap.name);
    }
  }, [id, mapId]);

  const updateMap = (updates) => {
    const updatedMaps = maps.map(m => 
      m.id === mapId ? { ...m, ...updates } : m
    );
    setMaps(updatedMaps);
    writeMaps(id, updatedMaps);
    setMap(prev => ({ ...prev, ...updates }));
  };

  const handleNameSave = () => {
    if (mapName.trim()) {
      updateMap({ name: mapName.trim() });
      setIsEditingName(false);
    }
  };

  const handleImageUpload = (e) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        const imageUrl = event.target.result;
        updateMap({ backgroundImage: imageUrl });
      };
      reader.readAsDataURL(file);
    }
  };

  const handleCombineMaps = () => {
    if (selectedMaps.length < 2) {
      alert("Please select at least 2 maps to combine");
      return;
    }
    
    // Combine maps using AI
    setIsAIGenerating(true);
    
    // Simulate AI processing
    setTimeout(() => {
      const combinedMapName = `Combined Map ${Date.now()}`;
      const selectedMapData = selectedMaps.map(id => maps.find(m => m.id === id));
      
      // Create combined map
      const newMap = {
        id: crypto.randomUUID(),
        name: combinedMapName,
        type: map?.type || '2d-map',
        backgroundImage: null, // Will be generated by AI
        combinedFrom: selectedMaps,
        createdAt: Date.now(),
        tags: []
      };
      
      const updatedMaps = [...maps, newMap];
      setMaps(updatedMaps);
      writeMaps(id, updatedMaps);
      
      setShowCombineModal(false);
      setSelectedMaps([]);
      setIsAIGenerating(false);
      
      // Navigate to the new combined map
      router.push(`/dashboard/projects/${id}/maps/${newMap.id}`);
    }, 2000);
  };

  const handleAIGenerate = async () => {
    if (!aiPrompt.trim()) {
      alert("Please enter a prompt");
      return;
    }
    
    setIsAIGenerating(true);
    
    try {
      // Determine if this is an edit (map already has an image)
      const editMode = Boolean(map?.backgroundImage);
      
      // Call the map generation API
      const response = await fetch('/api/maps/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          prompt: aiPrompt.trim(),
          mapType: map?.type || '2d-map',
          existingImage: map?.backgroundImage || null,
          editMode: editMode
        }),
      });

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }

      const data = await response.json();

      if (data.success && data.mapImage) {
        updateMap({ backgroundImage: data.mapImage });
        setShowAIModal(false);
        setAiPrompt("");
      } else {
        throw new Error(data.error || 'Failed to generate map');
      }
    } catch (error) {
      console.error('Error generating map:', error);
      alert(`Failed to generate map: ${error.message || 'Please try again.'}`);
    } finally {
      setIsAIGenerating(false);
    }
  };

  const toggleMapSelection = (mapIdToToggle) => {
    setSelectedMaps(prev => 
      prev.includes(mapIdToToggle)
        ? prev.filter(id => id !== mapIdToToggle)
        : [...prev, mapIdToToggle]
    );
  };

  if (!map) {
    return (
      <div className={styles.page}>
        <div className={styles.loading}>Loading map...</div>
      </div>
    );
  }

  const mapTypeInfo = MAP_TYPES.find(t => t.id === map.type) || MAP_TYPES[0];
  const availableMapsForCombine = maps.filter(m => m.id !== mapId);

  return (
    <div className={styles.page}>
      {/* Header */}
      <header className={styles.header}>
        <button className={styles.backButton} onClick={() => router.push(`/dashboard/projects/${id}/maps`)}>
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M19 12H5M12 19l-7-7 7-7"/>
          </svg>
          Back to Maps
        </button>
        <div className={styles.headerContent}>
          {isEditingName ? (
            <div className={styles.nameEditor}>
              <input
                type="text"
                value={mapName}
                onChange={(e) => setMapName(e.target.value)}
                onBlur={handleNameSave}
                onKeyDown={(e) => e.key === 'Enter' && handleNameSave()}
                className={styles.nameInput}
                autoFocus
              />
              <button className={styles.saveButton} onClick={handleNameSave}>Save</button>
            </div>
          ) : (
            <h1 className={styles.title} onClick={() => setIsEditingName(true)}>
              {map.name}
              <svg className={styles.editIcon} width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
                <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
              </svg>
            </h1>
          )}
          <div className={styles.mapType}>
            <span className={styles.mapTypeIcon}>{mapTypeInfo.icon}</span>
            <span>{mapTypeInfo.name}</span>
          </div>
        </div>
      </header>

      <div className={styles.content}>
        {/* Settings Panel */}
        <aside className={styles.sidebar}>
          <div className={styles.settingsSection}>
            <h2>Settings</h2>
            
            <div className={styles.settingGroup}>
              <label>Background Image</label>
              <div className={styles.imageUpload}>
                {map.backgroundImage ? (
                  <div className={styles.imagePreview}>
                    <img src={map.backgroundImage} alt="Background" />
                    <button 
                      className={styles.removeImage}
                      onClick={() => updateMap({ backgroundImage: null })}
                    >
                      Remove
                    </button>
                  </div>
                ) : (
                  <button 
                    className={styles.uploadButton}
                    onClick={() => fileInputRef.current?.click()}
                  >
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                      <polyline points="17 8 12 3 7 8"></polyline>
                      <line x1="12" y1="3" x2="12" y2="15"></line>
                    </svg>
                    Upload Image
                  </button>
                )}
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/*"
                  onChange={handleImageUpload}
                  style={{ display: 'none' }}
                />
              </div>
            </div>

            <div className={styles.settingGroup}>
              <label>Map Actions</label>
              <div className={styles.actionButtons}>
                <button 
                  className={styles.actionButton}
                  onClick={() => setShowCombineModal(true)}
                >
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M8 3H5a2 2 0 0 0-2 2v3m18 0V5a2 2 0 0 0-2-2h-3m0 18h3a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2h3"></path>
                  </svg>
                  Combine Maps
                </button>
                <button 
                  className={styles.actionButton}
                  onClick={() => setShowAIModal(true)}
                >
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M12 2L2 7l10 5 10-5-10-5z"></path>
                    <path d="M2 17l10 5 10-5"></path>
                    <path d="M2 12l10 5 10-5"></path>
                  </svg>
                  AI Assistant
                </button>
              </div>
            </div>
          </div>
        </aside>

        {/* Map Viewer */}
        <main className={styles.mapViewer}>
          <div className={styles.mapContainer}>
            {map.backgroundImage ? (
              <img 
                src={map.backgroundImage} 
                alt={map.name}
                className={styles.mapImage}
              />
            ) : (
              <div className={styles.mapPlaceholder}>
                <div className={styles.placeholderIcon}>{mapTypeInfo.icon}</div>
                <h3>{map.name}</h3>
                <p>Upload a background image or use AI to generate one</p>
              </div>
            )}
          </div>
        </main>
      </div>

      {/* Combine Maps Modal */}
      {showCombineModal && (
        <div className={styles.modalOverlay} onClick={() => setShowCombineModal(false)}>
          <div className={styles.modal} onClick={(e) => e.stopPropagation()}>
            <div className={styles.modalHeader}>
              <h2>Combine Maps</h2>
              <button className={styles.modalClose} onClick={() => setShowCombineModal(false)}>×</button>
            </div>
            <p className={styles.modalDescription}>
              Select maps to combine. AI will merge them into a new map.
            </p>
            <div className={styles.mapSelection}>
              {availableMapsForCombine.map(m => {
                const isSelected = selectedMaps.includes(m.id);
                return (
                  <div
                    key={m.id}
                    className={`${styles.mapOption} ${isSelected ? styles.selected : ''}`}
                    onClick={() => toggleMapSelection(m.id)}
                  >
                    <div className={styles.mapOptionCheck}>
                      {isSelected && <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                        <polyline points="20 6 9 17 4 12"></polyline>
                      </svg>}
                    </div>
                    <div className={styles.mapOptionContent}>
                      <div className={styles.mapOptionName}>{m.name}</div>
                      <div className={styles.mapOptionType}>{MAP_TYPES.find(t => t.id === m.type)?.name}</div>
                    </div>
                  </div>
                );
              })}
            </div>
            <div className={styles.modalActions}>
              <button className={styles.cancelButton} onClick={() => setShowCombineModal(false)}>
                Cancel
              </button>
              <button 
                className={styles.primaryButton}
                onClick={handleCombineMaps}
                disabled={selectedMaps.length < 2 || isAIGenerating}
              >
                {isAIGenerating ? 'Brewing Map...' : `Brew New Map (${selectedMaps.length} maps)`}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* AI Assistant Modal */}
      {showAIModal && (
        <div className={styles.modalOverlay} onClick={() => setShowAIModal(false)}>
          <div className={styles.modal} onClick={(e) => e.stopPropagation()}>
            <div className={styles.modalHeader}>
              <h2>AI Map Builder</h2>
              <button className={styles.modalClose} onClick={() => setShowAIModal(false)}>×</button>
            </div>
            <p className={styles.modalDescription}>
              {map?.backgroundImage 
                ? "Describe the changes you want to make to the map. AI will modify it for you."
                : "Describe the map you want to create. AI will generate it for you."}
            </p>
            <div className={styles.aiInput}>
              <textarea
                value={aiPrompt}
                onChange={(e) => setAiPrompt(e.target.value)}
                placeholder={map?.backgroundImage 
                  ? "E.g., 'Remove the green pipes' or 'Add more clouds' or 'Change the sky to sunset colors'"
                  : "E.g., 'Flappy bird map without pipes' or 'A tropical island with palm trees and a beach'"}
                className={styles.aiTextarea}
                rows={4}
              />
              <div className={styles.aiExamples}>
                <span>Examples:</span>
                {map?.backgroundImage ? (
                  <>
                    <button onClick={() => setAiPrompt("Remove the green pipes")}>
                      Remove Pipes
                    </button>
                    <button onClick={() => setAiPrompt("Add more clouds")}>
                      Add Clouds
                    </button>
                    <button onClick={() => setAiPrompt("Change sky to sunset colors")}>
                      Sunset Sky
                    </button>
                  </>
                ) : (
                  <>
                    <button onClick={() => setAiPrompt("Flappy bird map without pipes")}>
                      Flappy Bird (No Pipes)
                    </button>
                    <button onClick={() => setAiPrompt("A tropical island with palm trees and a beach")}>
                      Tropical Island
                    </button>
                    <button onClick={() => setAiPrompt("A medieval castle on a hill")}>
                      Medieval Castle
                    </button>
                  </>
                )}
              </div>
            </div>
            <div className={styles.modalActions}>
              <button className={styles.cancelButton} onClick={() => setShowAIModal(false)}>
                Cancel
              </button>
              <button 
                className={styles.primaryButton}
                onClick={handleAIGenerate}
                disabled={!aiPrompt.trim() || isAIGenerating}
              >
                {isAIGenerating ? (map?.backgroundImage ? 'Updating...' : 'Generating...') : (map?.backgroundImage ? 'Update Map' : 'Generate Map')}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

